name: test-calc-actions
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Maven install
        run: |
          pwd
          cd presto
          mvn install -DskipTests
      - name: Maven tests
        run: |
          cd presto
          mvn test -Dtest=com.mycompany.app.AppTest#testAddition
